[build]
  command = "npm install --ignore-scripts && npm rebuild && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.2"
  NODE_OPTIONS = "--openssl-legacy-provider"
  LIGHTNING_CSS_FORCE_NODE = "true"
